name: Check if forecast date is in season

on:
  workflow_call:
    outputs:
      in_season:
        description: "Whether a forecast should run"
        value: ${{ jobs.check_in_season.outputs.in_season }}

  workflow_dispatch:

jobs:

  check_in_season:
    runs-on: ubuntu-latest

    outputs:
      in_season: ${{ steps.job_id.outputs.in_season }}

    steps:
      - id: job_id  # gh uses id to reference output
        name: check_in_season
        shell: bash
        run: |

          TODAY=$(date -u +%F)
          YEAR=$(date -u +%Y)
          MONTH=$(date -u +%m)

          echo "Today is $TODAY"
          echo "Event is ${{ github.event_name }}"

          # manual dispatch always allowed
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "in_season=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ $MONTH -ge 10 ]]; then
            START_DATE="${YEAR}-10-07"
            END_DATE="$((YEAR + 1))-05-28"
          else
            START_DATE="$((YEAR - 1))-10-07"
            END_DATE="${YEAR}-05-28"
          fi

          echo "Season start: $START_DATE"
          echo "Season end:   $END_DATE"

          if [[ "$TODAY" > "$START_DATE" || "$TODAY" == "$START_DATE" ]] && \
             [[ "$TODAY" < "$END_DATE"   || "$TODAY" == "$END_DATE" ]]; then

            echo "in_season=true" >> $GITHUB_OUTPUT

          else
            echo "in_season=false" >> $GITHUB_OUTPUT
          fi