name: Validate model setup

on:
  workflow_dispatch:

jobs:
  validate_model_setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest',]
    steps:
    - uses: actions/checkout@v5

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v4
      with:
        activate-environment: HIERARCHSIR
        environment-file: HIERARCHSIR_conda-env.yml

    - name: Install Boost Libraries
      shell: bash -l {0}
      run: |
        conda activate HIERARCHSIR
        sudo -n apt-get update && sudo -n apt-get install -y libboost-all-dev

    - name: Install model code in HIERARCHSIR 
      shell: bash -l {0}
      run: |
        conda activate HIERARCHSIR
        python -m pip install --upgrade pip
        pip install -e . --force-reinstall